import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
// import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });
import React from "react";
import SearchAppBar from "@/components/navbar";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "PAK PANTRY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchAppBar/>
        <AuthProvider>{children}</AuthProvider>
        </body>
    </html>
  );
}
